### PR TITLE
go client implementation

### PR DESCRIPTION
**Pull request by mqliang**
I mistakenly close https://github.com/zaproxy/zap-api-go/pull/2 when squashing. Reopen it here.

@kingthorin Now, the pr is well squashed. I didn't squash them into a single commit, instead I squash them into several independent commits for easy of review.

cc @thc202 @psiinon

### CODE REVIEW

**Comment by kingthorin** [comment]
Thanks

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thanks!

The generated code could be updated for ZAP 2.7.0 but I'm OK with that being done in another pull request.

**Comment by mqliang** [comment]
Can this be merged, so that I can send a following PR to update it to ZAP 2.7.0. ?

**Comment by thc202** [comment]
@psiinon, @kingthorin looks good?

**Review by kingthorin — APPROVED** [review]
I don't have any go experience/exposure, but I don't see any obvious issues.

**Review by psiinon — APPROVED** [review]
Looks good, as far as I can tell ;)

**Pull request merged**
